import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4321/', { waitUntil: 'networkidle' });
const h1 = await page.locator('h1').first();
const font = await h1.evaluate(el => getComputedStyle(el).fontFamily);
const weight = await h1.evaluate(el => getComputedStyle(el).fontWeight);
console.log('H1 font:', font, 'weight:', weight);
const body = await page.evaluate(() => getComputedStyle(document.body).fontFamily);
console.log('Body font:', body);
await browser.close();
